import type { FleetData } from "./types";

/**
 * Fleet demo seed built around the real Empresa Plana lines of the Costa
 * Daurada (mirrors app/data/popular-lines.json). Coordinates are approximate
 * (map demo). Values are fixed so charts don't flicker between renders.
 */
export const FLEET_SEED: FleetData = {
	routes: [
		{
			id: "barcelonaAirport",
			code: "BCN-AER",
			name: "Barcelona – Aeropuerto",
			origin: "Cambrils",
			destination: "Barcelona",
			color: "#013990",
			status: "active",
			path: [
				[41.07, 1.058],
				[41.0733, 1.131],
				[41.0753, 1.1807],
				[41.1189, 1.2445],
				[41.219, 1.533],
				[41.234, 1.811],
				[41.2888, 2.073],
				[41.297, 2.098],
				[41.3915, 2.181],
			],
		},
		{
			id: "tarragonaBarcelona",
			code: "TGN-BCN",
			name: "Tarragona – Barcelona",
			origin: "Tarragona",
			destination: "Barcelona",
			color: "#00696F",
			status: "active",
			path: [
				[41.1189, 1.2445],
				[41.219, 1.533],
				[41.234, 1.811],
				[41.297, 2.098],
				[41.3915, 2.181],
			],
		},
		{
			id: "costaDorada",
			code: "COSTA",
			name: "Costa Daurada",
			origin: "Tarragona",
			destination: "Cambrils",
			color: "#13AEB8",
			status: "active",
			path: [
				[41.1189, 1.2445],
				[41.1108, 1.1447],
				[41.0753, 1.1807],
				[41.0733, 1.131],
				[41.07, 1.058],
			],
		},
		{
			id: "penedes",
			code: "L68",
			name: "Vilanova i la Geltrú – Vilafranca",
			origin: "Vilanova i la Geltrú",
			destination: "Vilafranca del Penedès",
			color: "#EB8E02",
			status: "delayed",
			path: [
				[41.224, 1.725],
				[41.208, 1.672],
				[41.346, 1.699],
			],
		},
		{
			id: "estacioCamp",
			code: "TGN-CAMP",
			name: "Tarragona – Estació del Camp",
			origin: "Tarragona",
			destination: "Estació del Camp AVE",
			color: "#0E7490",
			status: "active",
			path: [
				[41.1189, 1.2445],
				[41.153, 1.214],
				[41.191, 1.252],
			],
		},
		{
			id: "ametllaTortosa",
			code: "AME-TOR",
			name: "L'Ametlla de Mar – Tortosa",
			origin: "L'Ametlla de Mar",
			destination: "Tortosa",
			color: "#7C3AED",
			status: "active",
			path: [
				[40.884, 0.803],
				[40.875, 0.713],
				[40.813, 0.708],
				[40.772, 0.672],
				[40.741, 0.615],
				[40.8125, 0.5215],
			],
		},
		{
			id: "reusSalou",
			code: "e5",
			name: "Reus – Salou",
			origin: "Reus",
			destination: "Salou",
			color: "#C2410C",
			status: "active",
			path: [
				[41.1557, 1.107],
				[41.1474, 1.1672],
				[41.0876, 1.1549],
				[41.0733, 1.131],
			],
		},
		{
			id: "tarragonaVilasecaSalou",
			code: "TGN-VSS",
			name: "Tarragona – Vila-seca – Salou",
			origin: "Tarragona",
			destination: "Salou",
			color: "#4D7C0F",
			status: "inactive",
			path: [
				[41.1189, 1.2445],
				[41.1108, 1.1447],
				[41.0733, 1.131],
			],
		},
	],
	buses: [
		{
			id: 1,
			number: "BUS-001",
			plate: "1234 ABC",
			company: "Empresa Plana",
			capacity: 55,
			routeId: "barcelonaAirport",
			status: "active",
			gps: { lat: 41.1189, lng: 1.2445, speed: 72, battery: 94, online: true },
		},
		{
			id: 2,
			number: "BUS-002",
			plate: "5678 DEF",
			company: "Empresa Plana",
			capacity: 55,
			routeId: "barcelonaAirport",
			status: "active",
			gps: { lat: 41.234, lng: 1.811, speed: 66, battery: 88, online: true },
		},
		{
			id: 3,
			number: "BUS-003",
			plate: "9012 GHI",
			company: "Empresa Plana",
			capacity: 50,
			routeId: "tarragonaBarcelona",
			status: "active",
			gps: { lat: 41.219, lng: 1.533, speed: 78, battery: 91, online: true },
		},
		{
			id: 4,
			number: "BUS-004",
			plate: "3456 JKL",
			company: "Empresa Plana",
			capacity: 40,
			routeId: "costaDorada",
			status: "active",
			gps: { lat: 41.0753, lng: 1.1807, speed: 45, battery: 83, online: true },
		},
		{
			id: 5,
			number: "BUS-005",
			plate: "7890 MNO",
			company: "Empresa Plana",
			capacity: 35,
			routeId: "penedes",
			status: "maintenance",
			gps: { lat: 41.208, lng: 1.672, speed: 0, battery: 45, online: false },
		},
		{
			id: 6,
			number: "BUS-006",
			plate: "1122 PQR",
			company: "Empresa Plana",
			capacity: 50,
			routeId: "penedes",
			status: "active",
			gps: { lat: 41.346, lng: 1.699, speed: 58, battery: 79, online: true },
		},
		{
			id: 7,
			number: "BUS-007",
			plate: "3344 STU",
			company: "Empresa Plana",
			capacity: 40,
			routeId: "estacioCamp",
			status: "active",
			gps: { lat: 41.191, lng: 1.252, speed: 52, battery: 90, online: true },
		},
		{
			id: 8,
			number: "BUS-008",
			plate: "5566 VWX",
			company: "Empresa Plana",
			capacity: 55,
			routeId: "ametllaTortosa",
			status: "active",
			gps: { lat: 40.813, lng: 0.708, speed: 63, battery: 86, online: true },
		},
		{
			id: 9,
			number: "BUS-009",
			plate: "7788 YZA",
			company: "Empresa Plana",
			capacity: 35,
			routeId: "reusSalou",
			status: "active",
			gps: { lat: 41.0876, lng: 1.1549, speed: 48, battery: 74, online: true },
		},
		{
			id: 10,
			number: "BUS-010",
			plate: "9900 BCD",
			company: "Empresa Plana",
			capacity: 40,
			routeId: "tarragonaVilasecaSalou",
			status: "inactive",
			gps: { lat: 41.1189, lng: 1.2445, speed: 0, battery: 61, online: false },
		},
	],
	stops: [
		{
			id: 1,
			name: "Barcelona · Estació Nord",
			address: "C/ d'Ali Bei, 80",
			lat: 41.3915,
			lng: 2.181,
			routes: ["barcelonaAirport", "tarragonaBarcelona"],
		},
		{
			id: 2,
			name: "Aeropuerto de Barcelona · T1",
			address: "El Prat de Llobregat",
			lat: 41.2888,
			lng: 2.073,
			routes: ["barcelonaAirport"],
		},
		{
			id: 3,
			name: "Sitges",
			address: "Estació d'autobusos",
			lat: 41.234,
			lng: 1.811,
			routes: ["barcelonaAirport", "tarragonaBarcelona"],
		},
		{
			id: 4,
			name: "El Vendrell",
			address: "Ctra. N-340",
			lat: 41.219,
			lng: 1.533,
			routes: ["barcelonaAirport", "tarragonaBarcelona"],
		},
		{
			id: 5,
			name: "Tarragona · Rambla Nova",
			address: "Rambla Nova, 45",
			lat: 41.1189,
			lng: 1.2445,
			routes: [
				"barcelonaAirport",
				"tarragonaBarcelona",
				"costaDorada",
				"estacioCamp",
				"tarragonaVilasecaSalou",
			],
		},
		{
			id: 6,
			name: "La Pineda",
			address: "Av. de la Diputació",
			lat: 41.0753,
			lng: 1.1807,
			routes: ["barcelonaAirport", "costaDorada"],
		},
		{
			id: 7,
			name: "Salou · Estació",
			address: "C/ de Barcelona",
			lat: 41.0733,
			lng: 1.131,
			routes: [
				"barcelonaAirport",
				"costaDorada",
				"reusSalou",
				"tarragonaVilasecaSalou",
			],
		},
		{
			id: 8,
			name: "Cambrils · Av. Diputació",
			address: "Pl. del Mercat",
			lat: 41.07,
			lng: 1.058,
			routes: ["barcelonaAirport", "costaDorada"],
		},
		{
			id: 9,
			name: "Vila-seca",
			address: "C/ Major",
			lat: 41.1108,
			lng: 1.1447,
			routes: ["costaDorada", "tarragonaVilasecaSalou"],
		},
		{
			id: 10,
			name: "PortAventura",
			address: "Av. Alcalde Pere Molas",
			lat: 41.0876,
			lng: 1.1549,
			routes: ["reusSalou"],
		},
		{
			id: 11,
			name: "Aeropuerto de Reus",
			address: "Ctra. T-11",
			lat: 41.1474,
			lng: 1.1672,
			routes: ["reusSalou"],
		},
		{
			id: 12,
			name: "Reus · Pl. del Mercadal",
			address: "Pl. del Mercadal",
			lat: 41.1557,
			lng: 1.107,
			routes: ["reusSalou"],
		},
		{
			id: 13,
			name: "Vilanova i la Geltrú",
			address: "Estació d'autobusos",
			lat: 41.224,
			lng: 1.725,
			routes: ["penedes"],
		},
		{
			id: 14,
			name: "Cubelles",
			address: "C/ de l'Estació",
			lat: 41.208,
			lng: 1.672,
			routes: ["penedes"],
		},
		{
			id: 15,
			name: "Vilafranca del Penedès",
			address: "Estació d'autobusos",
			lat: 41.346,
			lng: 1.699,
			routes: ["penedes"],
		},
		{
			id: 16,
			name: "Estació del Camp · AVE",
			address: "La Secuita",
			lat: 41.191,
			lng: 1.252,
			routes: ["estacioCamp"],
		},
		{
			id: 17,
			name: "Constantí",
			address: "C/ Les Creus",
			lat: 41.153,
			lng: 1.214,
			routes: ["estacioCamp"],
		},
		{
			id: 18,
			name: "L'Ametlla de Mar",
			address: "Ctra. N-340",
			lat: 40.884,
			lng: 0.803,
			routes: ["ametllaTortosa"],
		},
		{
			id: 19,
			name: "L'Ampolla",
			address: "Av. del Mar",
			lat: 40.813,
			lng: 0.708,
			routes: ["ametllaTortosa"],
		},
		{
			id: 20,
			name: "Tortosa · Estació",
			address: "Pl. de l'Estació",
			lat: 40.8125,
			lng: 0.5215,
			routes: ["ametllaTortosa"],
		},
	],
	schedules: [
		{
			id: 1,
			routeId: "barcelonaAirport",
			departure: "06:30",
			arrival: "08:15",
			frequency: "60 min",
			days: "Lun–Dom",
			status: "active",
		},
		{
			id: 2,
			routeId: "barcelonaAirport",
			departure: "17:00",
			arrival: "18:45",
			frequency: "60 min",
			days: "Lun–Dom",
			status: "active",
		},
		{
			id: 3,
			routeId: "tarragonaBarcelona",
			departure: "07:00",
			arrival: "08:30",
			frequency: "45 min",
			days: "Lun–Vie",
			status: "active",
		},
		{
			id: 4,
			routeId: "costaDorada",
			departure: "07:15",
			arrival: "07:50",
			frequency: "30 min",
			days: "Lun–Dom",
			status: "active",
		},
		{
			id: 5,
			routeId: "penedes",
			departure: "06:50",
			arrival: "07:35",
			frequency: "60 min",
			days: "Lun–Vie",
			status: "active",
		},
		{
			id: 6,
			routeId: "penedes",
			departure: "16:30",
			arrival: "17:15",
			frequency: "60 min",
			days: "Lun–Vie",
			status: "active",
		},
		{
			id: 7,
			routeId: "estacioCamp",
			departure: "05:50",
			arrival: "06:05",
			frequency: "60 min",
			days: "Lun–Dom",
			status: "active",
		},
		{
			id: 8,
			routeId: "ametllaTortosa",
			departure: "07:00",
			arrival: "08:30",
			frequency: "120 min",
			days: "Lun–Vie",
			status: "active",
		},
		{
			id: 9,
			routeId: "reusSalou",
			departure: "08:00",
			arrival: "08:25",
			frequency: "30 min",
			days: "Lun–Dom",
			status: "active",
		},
		{
			id: 10,
			routeId: "tarragonaVilasecaSalou",
			departure: "07:20",
			arrival: "07:45",
			frequency: "45 min",
			days: "Lun–Sáb",
			status: "inactive",
		},
	],
	drivers: [
		{
			id: 1,
			name: "Joan García",
			phone: "+34 612 345 678",
			license: "D12345678",
			busNumber: "BUS-001",
			routeId: "barcelonaAirport",
			shiftDays: "Lun–Dom",
			shiftHours: "06:00–14:00",
			status: "active",
		},
		{
			id: 2,
			name: "Maria López",
			phone: "+34 623 456 789",
			license: "D23456789",
			busNumber: "BUS-002",
			routeId: "tarragonaBarcelona",
			shiftDays: "Lun–Vie",
			shiftHours: "07:00–15:00",
			status: "active",
		},
		{
			id: 3,
			name: "Pere Martí",
			phone: "+34 634 567 890",
			license: "D34567890",
			busNumber: "BUS-003",
			routeId: "costaDorada",
			shiftDays: "Lun–Sáb",
			shiftHours: "06:30–14:30",
			status: "active",
		},
		{
			id: 4,
			name: "Anna Puig",
			phone: "+34 645 678 901",
			license: "D45678901",
			busNumber: "BUS-004",
			routeId: "penedes",
			shiftDays: "Lun–Vie",
			shiftHours: "05:30–13:30",
			status: "active",
		},
		{
			id: 5,
			name: "Jordi Vila",
			phone: "+34 656 789 012",
			license: "D56789012",
			busNumber: "BUS-005",
			routeId: "reusSalou",
			shiftDays: "Lun–Vie",
			shiftHours: "07:00–15:00",
			status: "inactive",
		},
		{
			id: 6,
			name: "Núria Soler",
			phone: "+34 667 890 123",
			license: "D67890123",
			busNumber: "BUS-006",
			routeId: "estacioCamp",
			shiftDays: "Lun–Dom",
			shiftHours: "05:00–13:00",
			status: "active",
		},
		{
			id: 7,
			name: "Carles Ferrer",
			phone: "+34 678 901 234",
			license: "D78901234",
			busNumber: "BUS-007",
			routeId: "ametllaTortosa",
			shiftDays: "Lun–Vie",
			shiftHours: "06:00–14:00",
			status: "active",
		},
		{
			id: 8,
			name: "Marta Rius",
			phone: "+34 689 012 345",
			license: "D89012345",
			busNumber: "BUS-008",
			routeId: "tarragonaVilasecaSalou",
			shiftDays: "Lun–Sáb",
			shiftHours: "07:00–15:00",
			status: "active",
		},
	],
	notifications: [
		{
			id: 1,
			type: "delay",
			title: "Retraso en la L68",
			desc: "La línea L68 circula con +5 min por retención en la C-15 a la altura de Vilafranca.",
			createdAt: new Date(Date.now() - 10 * 60_000).toISOString(),
			read: false,
			routeId: "penedes",
		},
		{
			id: 2,
			type: "accident",
			title: "Incidente en la AP-7",
			desc: "Tráfico lento en la AP-7 entre El Vendrell y Sitges. Salidas con hasta 15 min de demora.",
			createdAt: new Date(Date.now() - 40 * 60_000).toISOString(),
			read: false,
			routeId: "tarragonaBarcelona",
		},
		{
			id: 3,
			type: "detour",
			title: "Desvío por obras en Tortosa",
			desc: "Obras en la N-340: la línea del Ebro entra por el acceso norte de Tortosa.",
			createdAt: new Date(Date.now() - 3 * 3600_000).toISOString(),
			read: false,
			routeId: "ametllaTortosa",
		},
		{
			id: 4,
			type: "info",
			title: "Nuevo horario de la e5",
			desc: "A partir del lunes la frecuencia de la e5 Reus–Salou pasa a ser de 30 minutos en hora punta.",
			createdAt: new Date(Date.now() - 26 * 3600_000).toISOString(),
			read: true,
			routeId: "reusSalou",
		},
	],
	activity: [
		{
			id: 4,
			at: new Date(Date.now() - 12 * 60_000).toISOString(),
			action: "Ruta TGN-BCN actualizada",
			user: "Sergi Plana",
		},
		{
			id: 3,
			at: new Date(Date.now() - 45 * 60_000).toISOString(),
			action: "Nuevo conductor añadido: Marta Rius",
			user: "Sergi Plana",
		},
		{
			id: 2,
			at: new Date(Date.now() - 2 * 3600_000).toISOString(),
			action: "Parada «Vilafranca del Penedès» editada",
			user: "Sergi Plana",
		},
		{
			id: 1,
			at: new Date(Date.now() - 5 * 3600_000).toISOString(),
			action: "Sincronización MOTIS completada",
			user: "Sistema",
		},
	],
	reports: {
		passengers: {
			barcelonaAirport: 2450,
			tarragonaBarcelona: 3200,
			costaDorada: 1800,
			penedes: 950,
			estacioCamp: 420,
			ametllaTortosa: 620,
			reusSalou: 2100,
			tarragonaVilasecaSalou: 1500,
		},
		occupancy: {
			barcelonaAirport: 88,
			tarragonaBarcelona: 92,
			costaDorada: 76,
			penedes: 64,
			estacioCamp: 55,
			ametllaTortosa: 48,
			reusSalou: 85,
			tarragonaVilasecaSalou: 71,
		},
		weeklyPunctuality: [94, 96, 92, 95, 93, 90, 88],
		satisfaction: [
			{ name: "punctuality", value: 94 },
			{ name: "cleanliness", value: 87 },
			{ name: "comfort", value: 82 },
			{ name: "information", value: 91 },
			{ name: "attention", value: 89 },
		],
	},
	config: {
		motisUrl: "http://localhost:8080",
		traccarUrl: "https://traccar.empresaplana.cat",
		traccarProtocol: "OSMAND",
	},
};
